""" 
Artificial Intelligence (AI) is a branch of Computer Science that enables machines to simulate human intelligence by performing tasks like learning, reasoning, and recognizing images or speech.
 TWO BRANCHES -> Machine Learning and Another is Deep Learning and one more that is another than that is robotics okey


LOGIC AND INPUT GIVES TO -> TRADITIONAL SYSTEM PROGRAM -> IT GIVES US OUTPUT 
INPUT AND OUTPUT GIVES TO ->ML TRAINING -> CREATE MODEL THAT CONTAINS LOGIC ->ML INFERNCE -> NOW WE USE OUT NEW INPUT AND IT GIVES US OUTPUT 

Machine Learning allows systems to learn from data without explicit programming.
CLASSIFICATON AND REGRESSION AND TWO DIFF THINGS 

CLASSIFICATION MEANS FIX OUTPUT LIKE SPAN OR NOT SPAM IN MAIL EX
IN REGRESSION MEANS NO PREDICTION OF FIX DATA LIKE IN PREDICTION IOF PROICE OF NEW HOUSE COMES INTO MARKET .

SUPEVISED LEARNING AND UNSUPERVISED LEARNING 
IN SL THE DATA IS A LABELED RIGHT NO CLUSTERS LIKE THERE IS  ALIGNMENT OF THE DATA LIKE IN FORM OF TABLES 
IN USL IN WHICH DATA IS NOT LABELED IT IS MIXED , UNLABELED IT UNDERSTAND BY RECONGNIE THE PATTERNS LIKE CLUSTERING .

DEEP LEARNING 
NEURAL NETWORKS 
BACKWARD ERROR PROPOGATION N TIMES 
WHICH ONE TO CHOOSE STATISTICAL ML OR DEEP LEARNING 
SMALL DATASETS , LIMITED COMPUTE RESOURCES AND INTERPRETABLITLIY THEN USJE ML 
IF  BIG DATASETS COMPLEX FEATURES IMAGES VIDEO AND AUDIOO AND ENOUGH COMPUTER RESOURCES THEN USE DL 

ARCHITECTUER OF NEURAL NETWORK  -> FFN , RNN , CNN , TRANSFORMERS
IN FNN LIKE A JUICER MACHINE WE DONT KNOW THE PROCESS BEHIND THAT JUST OUTPUT 
IN RNN LIKE WE MAKE A SOUP AND PUT ONE BY ONE INGRIDIENTS IF THERE IS SOMETHING ODD THEN WE USE SOME MORE INGRIDIENCES BY GETTING FEEDBACK RIGHT 
IN TRANSFORMER LIKE A CHATGPT GIVE COMMAND POEN ON SAMOSA RECIPIE THEN HE RYM AND GIVETO US BECAUSE OF TRANSFORMER ACHITECTURE 


TOOLING FOR DL
PYTORCH BY META MORE BEGIINER FRIENDLY 
TENSERFLOW BY GOOGLE  
AND ANOTHER ONE IS GPU BECAUSE THERE IS HUG VOLUME OF DATA 

GENAI-> 
NOW MODELS FOR ALL THE CATEGORIES 
TEXT-MODELS -> GPT,LLAMA ,GEMINI,CLAUDE 
IMAGE MODELS -> DALL-E ,STABLE DIFFUSION 
AUDIO MODELS->AUDIO GEN , MUSIC LM 
VIDEO MODELS -> SORA 
""" 


